# Generated by Django 2.2 on 2020-09-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200906_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_text_html',
        ),
    ]
