# Generated by Django 2.2 on 2020-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200907_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\TotEu\\Desktop\\NewDjango\\DjangoNewsSite\\media'),
        ),
    ]
